from src.utils.format import SteamID

import json

TF2BD_ATTRIBUTES = ["cheater", "suspicious", "exploiter", "racist"]

def format_tf2bd(ids, listname="Bot", attrib_idx=1, proof="generated by BotListConverter"):
    for idx, single_attribute in enumerate(TF2BD_ATTRIBUTES):
        print(f"{idx + 1}. {single_attribute}")
        
    attrib_idx = int(input(f"Which label do you want to assign for the '{listname}' list? ")) or 1
    attributes = TF2BD_ATTRIBUTES[attrib_idx - 1]
    
    players = []
    for id in ids:
        id32 = SteamID(id).id3b
        players.append({
            "attributes": [attributes],
            "proof": [proof],
            "steamid": id32
        })
    
    data = {
        "$schema": "https://raw.githubusercontent.com/PazerOP/tf2_bot_detector/master/schemas/v3/playerlist.schema.json",
        "file_info": {
            "authors": ["Pianta", "BotListConverter"],
            "description": f"generated by BotListConverter - list '{listname}'",
            "title": "BotListConverter",
        },
        "players": players
    }
    
    return json.dumps(data, indent=4)

_ext = ".json"
def _main(lst, listname):
    # does not support dict
    if isinstance(lst, list):
        return format_tf2bd(lst, listname)
    else:
        for category in lst:
            lst[category] = format_tf2bd(lst[category], category)
        return lst